[versions]
complie-sdk = "36"
target-sdk = "36"
min-sdk = "26"
java-version = "21"
agp = "8.13.1"
kotlin = "2.2.21"
ksp = "2.2.20-2.0.3"
androidTools = "31.13.1"
android = "1.17.0"
compose = "1.9.5"
constraintlayoutCompose = "1.1.1"
lifecycle = "2.10.0"
room = "2.8.4"
#Warning: Update version of Media3. This may affect background playback functionality
#noinspection GradleDependency
media3 = "1.3.1"
media = "1.7.1"
coil3 = "3.3.0"
ktor = "3.3.3"
roomKtx = "2.8.4"
timber = "5.0.1"
koin = "4.1.1"
material3 = "1.4.0"
uiGraphics = "1.9.5"


[libraries]

# Core
androidx-core-ktx = { module = "androidx.core:core-ktx", version.ref = "android" }
androidx-animation = { module = "androidx.compose.animation:animation", version.ref = "compose" }
androidx-constraintlayout-compose = { module = "androidx.constraintlayout:constraintlayout-compose", version.ref = "constraintlayoutCompose" }

# Lifecycle
androidx-lifecycle-runtime-ktx = { module = "androidx.lifecycle:lifecycle-runtime-ktx", version.ref = "lifecycle" }
androidx-lifecycle-viewmodel-compose = { module = "androidx.lifecycle:lifecycle-viewmodel-compose", version.ref = "lifecycle" }
androidx-lifecycle-viewmodel-ktx = { module = "androidx.lifecycle:lifecycle-viewmodel-ktx", version.ref = "lifecycle" }

# Material
androidx-material3 = { module = "androidx.compose.material3:material3", version.ref = "material3" }

# Media
androidx-media = { module = "androidx.media:media", version.ref = "media" }
androidx-media3-ui = { module = "androidx.media3:media3-ui", version.ref = "media3" }
androidx-media3-common = { module = "androidx.media3:media3-common", version.ref = "media3" }
androidx-media3-session = { module = "androidx.media3:media3-session", version.ref = "media3" }
androidx-media3-exoplayer = { module = "androidx.media3:media3-exoplayer", version.ref = "media3" }
androidx-media3-exoplayer-dash = { module = "androidx.media3:media3-exoplayer-dash", version.ref = "media3" }
androidx-media3-datasource-okhttp = { module = "androidx.media3:media3-datasource-okhttp", version.ref = "media3" }

# Room
androidx-room-compiler = { module = "androidx.room:room-compiler", version.ref = "roomKtx" }
androidx-room-ktx = { module = "androidx.room:room-ktx", version.ref = "roomKtx" }
androidx-room-runtime = { module = "androidx.room:room-runtime", version.ref = "roomKtx" }

# Coil
coil-compose = { module = "io.coil-kt.coil3:coil-compose", version.ref = "coil3" }
coil-compose-core = { module = "io.coil-kt.coil3:coil-compose-core", version.ref = "coil3" }
coil-network-ktor3 = { module = "io.coil-kt.coil3:coil-network-ktor3", version.ref = "coil3" }
coil-mp = { module = "io.coil-kt.coil3:coil", version.ref = "coil3" }

# Ktor
gradle = { module = "com.android.tools.build:gradle", version.ref = "agp" }
ktor-client-auth = { module = "io.ktor:ktor-client-auth", version.ref = "ktor" }
ktor-client-core = { module = "io.ktor:ktor-client-core", version.ref = "ktor" }
ktor-client-okhttp = { module = "io.ktor:ktor-client-okhttp", version.ref = "ktor" }
ktor-client-logging = { module = "io.ktor:ktor-client-logging", version.ref = "ktor" }
ktor-client-encoding = { module = "io.ktor:ktor-client-encoding", version.ref = "ktor" }
ktor-client-content-negotiation = { module = "io.ktor:ktor-client-content-negotiation", version.ref = "ktor" }
ktor-serialization-kotlinx-json = { module = "io.ktor:ktor-serialization-kotlinx-json", version.ref = "ktor" }

# Koin
koin-core = { module = "io.insert-koin:koin-core", version.ref = "koin" }
koin-android = { module = "io.insert-koin:koin-android", version.ref = "koin" }
koin-compose = { module = "io.insert-koin:koin-compose-android", version.ref = "koin" }

timber = { module = "com.jakewharton.timber:timber", version.ref = "timber" }
android-gradleApiPlugin = { module = "com.android.tools.build:gradle-api", version.ref = "agp" }
android-tools-common = { module = "com.android.tools:common", version.ref = "androidTools" }
compose-gradlePlugin = { module = "org.jetbrains.kotlin:compose-compiler-gradle-plugin", version.ref = "kotlin" }
kotlin-gradlePlugin = { module = "org.jetbrains.kotlin:kotlin-gradle-plugin", version.ref = "kotlin" }
ksp-gradlePlugin = { module = "com.google.devtools.ksp:com.google.devtools.ksp.gradle.plugin", version.ref = "ksp" }
androidx-ui-graphics = { group = "androidx.compose.ui", name = "ui-graphics", version.ref = "uiGraphics" }

[plugins]
android-application = { id = "com.android.application", version.ref = "agp" }
android-library = { id = "com.android.library", version.ref = "agp" }
compose = { id = "org.jetbrains.kotlin.plugin.compose", version.ref = "kotlin" }
kotlin-jvm = { id = "org.jetbrains.kotlin.jvm", version.ref = "kotlin" }
kotlin-serialization = { id = "org.jetbrains.kotlin.plugin.serialization", version.ref = "kotlin" }
ksp = { id = "com.google.devtools.ksp", version.ref = "ksp" }
room = { id = "androidx.room", version.ref = "room" }

ndphuc-android-application = { id = "ndphuc.android.application" }
ndphuc-android-application-compose = { id = "ndphuc.android.application.compose" }
ndphuc-android-application-flavors = { id = "ndphuc.android.application.flavors" }
ndphuc-android-feature = { id = "ndphuc.android.feature" }
ndphuc-android-library = { id = "ndphuc.android.library" }
ndphuc-android-library-compose = { id = "ndphuc.android.library.compose" }
ndphuc-android-lint = { id = "ndphuc.android.lint" }
ndphuc-android-room = { id = "ndphuc.android.room" }
ndphuc-android-test = { id = "ndphuc.android.test" }
ndphuc-jvm-library = { id = "ndphuc.jvm.library" }
ndphuc-root = { id = "ndphuc.root" }

[bundles]
ktor = [
    "ktor-client-auth",
    "ktor-client-core",
    "ktor-client-okhttp",
    "ktor-client-logging",
    "ktor-client-encoding",
    "ktor-serialization-kotlinx-json",
    "ktor-client-content-negotiation"
]

coil = [
    "coil-compose",
    "coil-compose-core",
    "coil-network-ktor3",
    "coil-mp"
]

media3 = [
    "androidx-media",
    "androidx-media3-ui",
    "androidx-media3-common",
    "androidx-media3-session",
    "androidx-media3-exoplayer",
    "androidx-media3-exoplayer-dash",
    "androidx-media3-datasource-okhttp"
]
koin = [
    "koin-core",
    "koin-android",
]