name: presentation
publish_to: none

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  music:
    path: music
  shared_preferences: ^2.2.2
  share_plus: ^7.2.1
  rxdart: ^0.28.0
  flutter_bloc: ^9.1.1
  get_it: ^9.2.0
  injectable: ^2.7.1+2
  equatable: ^2.0.7

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  build_runner: ^2.10.4
  injectable_generator: ^2.11.1
  pigeon: ^26.1.4

flutter:
  uses-material-design: true

  module:
    androidX: true
    androidPackage: nd.phuc.presentation
