name: domain
version: 1.0.0
publish_to: none

environment:
  sdk: ">=3.7.2 <4.0.0"

dependencies:
  freezed_annotation: ^3.1.0
  json_annotation: ^4.9.0

dev_dependencies:
  build_runner: ^2.5.4
  freezed: ^3.1.0
  json_serializable: ^6.9.5
  lints: ^5.0.0
  test: ^1.24.0
